export const CHIP_FIELDS = [
    "TOP_MALWARE_PERMISSIONS",
    "PERMISSIONS",
    "OTHER_ABUSED_PERMISSIONS",
    "TRACKER_DETAILS",
    "DOMAINS",
    "CODE_ANALYSIS_MASVS",
    "CODE_ANALYSIS_CWE",
    "CODE_ANALYSIS_OWASP",
];